export const SEED_WORDS = [
  {
    english: "Hello",
    pinyin: "nǐ hǎo",
    character: "你好",
    category: "greetings",
    tags: ["basic", "common"],
    notes: "Universal Mandarin greeting.",
  },
  {
    english: "Thank you",
    pinyin: "xiè xie",
    character: "谢谢",
    category: "greetings",
    tags: ["polite"],
    notes: "Can be repeated twice for natural rhythm.",
  },
  {
    english: "Goodbye",
    pinyin: "zài jiàn",
    character: "再见",
    category: "greetings",
    tags: ["basic"],
    notes: "Literally 'again see'.",
  },
  {
    english: "Tea",
    pinyin: "chá",
    character: "茶",
    category: "food and drink",
    tags: ["beverage", "culture"],
    notes: "One character word.",
  },
  {
    english: "Coffee",
    pinyin: "kā fēi",
    character: "咖啡",
    category: "food and drink",
    tags: ["beverage"],
    notes: "Loanword from English/French.",
  },
  {
    english: "Dumplings",
    pinyin: "jiǎo zi",
    character: "饺子",
    category: "food and drink",
    tags: ["food", "tradition"],
    notes: "Traditional northern Chinese food.",
  },
  {
    english: "Water",
    pinyin: "shuǐ",
    character: "水",
    category: "food and drink",
    tags: ["essential"],
    notes: "Single character.",
  },
  {
    english: "Airport",
    pinyin: "jī chǎng",
    character: "机场",
    category: "travel",
    tags: ["transport", "places"],
    notes: "Literally 'machine field'.",
  },
  {
    english: "Subway / Metro",
    pinyin: "dì tiě",
    character: "地铁",
    category: "travel",
    tags: ["transport"],
    notes: "Literally 'earth iron'.",
  },
  {
    english: "Hotel",
    pinyin: "jiǔ diàn",
    character: "酒店",
    category: "travel",
    tags: ["accommodation"],
    notes: "Literally 'alcohol store' historically, modern hotel.",
  },
  {
    english: "Forbidden City",
    pinyin: "Gù gōng",
    character: "故宫",
    category: "Beijing landmarks",
    tags: ["history", "landmark"],
    notes: "Imperial palace complex in Beijing.",
  },
  {
    english: "Summer Palace",
    pinyin: "Yí hé yuán",
    character: "颐和园",
    category: "Beijing landmarks",
    tags: ["garden", "landmark"],
    notes: "Historic royal garden in Beijing.",
  },
  {
    english: "Today",
    pinyin: "jīn tiān",
    character: "今天",
    category: "time words",
    tags: ["daily"],
    notes: "Present day.",
  },
  {
    english: "Tomorrow",
    pinyin: "míng tiān",
    character: "明天",
    category: "time words",
    tags: ["future"],
    notes: "Literally 'bright day'.",
  },
  {
    english: "Friend",
    pinyin: "péng you",
    character: "朋友",
    category: "family",
    tags: ["people"],
    notes: "Common social relationship.",
  },
  {
    english: "Delicious",
    pinyin: "hǎo chī",
    character: "好吃",
    category: "adjectives",
    tags: ["food", "praise"],
    notes: "Literally 'good eat'.",
  },
];
